name: GuiAPI
version: 2.0.0
api-version: 1.17
authors: [Parzival]
main: io.github.parzivalExe.guiApi.GuiApiInitializer
commands:
  ItemEqualsTest:
    description: Test for ItemEquality
    usage: /itemEqualsTest
  GuiTest:
    description: GuiTest-Command
    usage: /guiTest
  guiAmount:
    description: Get the amount of Guis saved by the GuiManager
    usage: /guiAmount
  componentAmount:
    description: Get the amount of Components saved by the ComponentManager
    usage: /componentAmount
  guixml:
    description: create a Test-Gui from Test-XML
    usage: /guixml [GuiFile-Name]
  componentList:
    description: Get all the components currently registered
    usage: /componentList